### ISSUE TITLE
[TASK]: Add Magikarp Jump Subregion

### ISSUE THREAD

**Issue by Jaaslet** [pokeclicker/pokeclicker#3407]
### Task Description

- [x] Add the Magikarp Jump map as an Alolan subregion
- [x] Add the 10 leagues and a route leading up to the 10 leagues
- [x] Add all forms of Magikarp from the game #3410
- [x] Limit the attack in the subregion to only be damage from Magikarp #3532
- [x] Add battles. Each time you see a pattern for the first time, it should be given as a reward from the battle
  - [x] Last battle of each league should be a gym battle. Use name and Magikarp pattern from the games. #3450
  - [x] Each 5th battle, which is not the last, should be a temp battle #3451
  - [x] If the rest of the battles have any special patterns, add them to the route leading up to #3513
- [x] Add a short questline: You accept it in Alola and all you need to do is talk to the Mayor #3452
- [x] Add Mayor NPC. He will explain the area, the leagues and why you can only use magikarp attack there #3610
- [x] Add requirements! Do the leagues in order, and do the route before the league #3523
- [x] Adjust the SVG, so it looks nice #3459
- [x] Remove the 3 Expert leagues from the map #3459
- [x] Balance! (remember only Magikarps attack works)
  - [x] HP #3537
    - [x] Try again. The HP required is too little. Maybe x4 or x5 for the last league, and adjust the rest to follow that? #3594
  - [x] Money gained  #3589
- [x] Do a breeding balance, so we don't add 3 million mons with high breeding efficiency
- [x] See how many patterns are unobtainable, and find ways to add them. (roamers, shopmons, questlines) 
  - [x] Roamers #3513
  - [x] Shopmons #3554
- [x] Add the 10 badges #3410
- [x] Add enviroments #3588
- [x] Split into it's own achievement category #3452
- [ ] Rename all magikarps to be "Magikarp (Pattern name)"
- [x] Defeated messages #3528
- [x] Fill out the routes more. Repeat patterns and maybe do so the base karp spawns more often #3595
- [x] Temp battles are missing images #3571
- [x] Add questline with dr. spash. Do some training and collect some berries. Take one of the roamers as reward #3633

### Notes

- To test it in development, remove the NullRequirement from Subregions.ts
- Make sure every PR can be merge without the players being able to go there, before it's ready

### Issues Required For This Task

- #3406
