### ISSUE TITLE
[TASK]: Pokemon Contests

### ISSUE THREAD

**Issue by Farboo171** [pokeclicker/pokeclicker#3690]
### Task Description

Implement the Pokemon Contest, using the below drawings and notes:
Pokemon Contest structure and formulas:

Description:
Players will be able to enter the contest somewhere in Hoenn once per day.

Every day, a random style will be selected. Style points are a sum of the base stats: 
Cool = attack + specialDefense
Beautiful = specialAttack + defense
Cute = specialDefense + hitpoints
Clever = specialAttack + speed
Tough = hitpoints + defense

Every day, a random type will be selected. This type will be a filter, such that only pokemon of that type can be entered into the contest for that day.

Players will select three pokemon from the type filtered list, and the value of that pokemon for the given style will be calculated. For example, on a Cool style day with the Flying type filter, players could select Pidgey (Cool value of 80: 45 attack + 35 Special Defense), Lugia (Cool value of 244: 90 attack + 154 Special Defense), and Altaria (Cool value of 175: 70 attack + 105 Special Defense). This gives a total score of 499 Cool

After selecting these three mons for entry, players can boost their score with berries. The berries boots style scores as their flavor value, in the following manner:

Cool: Bitter
Beautiful: Dry
Cute: Sweet
Clever: Sour
Tough: Spicy

So in our example, a player could use one Jaboca berry on each mon, for 40 Bitter (Cool) points each, for a total of 120 additional Cool points. This brings the Grand Total for the entry to 639 Cool points for this example

After the player has selected their entry mons and berries, they will click the Enter Contest button. Their total score will be compared to a tiered reward system:

Normal Rank: 1-200
Super Rank: 201-450
Hyper Rank: 451-700
Master Rank: >700

Each tier will give out a different number of contest tokens as a reward, and presumably we will put an achievement on number of Master Rank wins.

UI:

Three tabs

Contest tab (Attached)
![contest_UI](https://user-images.githubusercontent.com/109317224/210178934-22b8d601-3536-45f0-9d4e-c479fdbc023a.png)

Prizes tab  (Attached)
![prizes_UI](https://user-images.githubusercontent.com/109317224/210178933-0fd3e978-f450-4084-bf2c-6bb53e5e3486.png)

Help tab:
(TBD, will be text)

The actual to-do's and assignees:

- [ ] Make UI for contests
- [ ] Make randomized Style and Type restrictions code
- [ ] Make code for calculating contest values based on selected pokemon
- [ ] Make code to add berrys to Style Point total
- [ ] Make contest reward tier packages
- [ ] Make code to award contest rewards
- [ ] Add Help Text (Eugene171)
- [ ] Add the location to the map
- [ ] Add funky mons (Eugene171 per #2958)
- [ ] Add shop with new currency (Eugene171)
- [ ] Add cosplaychus (Eugene171)
- [ ] Add tracked stats 
- [ ] Add achievements 

### Issues Required For This Task

None

**Comment by osherwott** [comment]
Oh no! This goes completely against my idea for contests! I wanted to add pokeblocks, hence my addition of smoothness to Berries :(
If you already have a plan then feel free to do this, but I'd really love to collaborate with you on contests if you'd let me!

**Comment by Farboo171** [comment]
I think that multiple ways to get Contest Tokens and multiple Contests are completely fine. If you have another way you want to implement them, putting them in a different region should be enough to justify two different approaches

**Comment by osherwott** [comment]
My two big desires are pokeblocks and ribbons. Do you think they could be implemented in your idea?

**Comment by osherwott** [comment]
As per guidelines, this also has [a thread on discord](https://discord.com/channels/450412847017754644/1059183326046453850)
