### ISSUE TITLE
[TASK]: Gigantamax

### ISSUE THREAD

**Issue by Qwertypop04** [pokeclicker/pokeclicker#3796]
### Task Description

Implement obtain system for Gigantamax Pokemon

New item (name undecided. Will be referred as Wishing Pieces for now) will be obtained from uncatchable temporary battles against Gigantamax Pokemon that will appear daily in the Wild Area, Isle of Armor and Crown Tundra

In the Master Dojo, will be a place you can exchange Wishing Pieces. Doing so, will add a random Gigantamax Pokemon to the boss list of the Max Lair, a new dungeon in the Crown Tundra.

- [ ] Add Max Lair dungeon
- [ ] Add Max Lair to map
- [ ] Add daily Gigantamax battles
- [ ] Add Wishing Pieces
- [ ] Add Wishing Piece exchange in Master Dojo

### Notes

- Must make sure no parts of the feature can be used until it is ready for release
- May want to give Gigantamax Urshifu and Eternamax Eternatus some sort of special requirement

### Issues Required For This Task

None

**Comment by Farboo171** [comment]
closing as this is well underway
