### ISSUE TITLE
[TASK]: Orre and the Shadow Pokemon

### ISSUE THREAD

**Issue by Farboo171** [pokeclicker/pokeclicker#4002]
### Task Description

Add Orre and shadow pokemon to the game as a Hoenn subregion.

### Notes

- [x] Make the map of Orre (Lucho)
- [x] Write the plot of Colosseum at Hoenn difficulty, populate all associated dungeons including environments (eugene171)
- [x] Write the plot of XD at Unova difficulty, populate all associated dungeons including environments (eugene171)
- [x] Create a Snagging mechanic (Jaaslet)
- [x] Create the Shadow status for pokemon (Jaaslet)
- [x] Create a Purified status for pokemon (Jaaslet)
- [x] Create an XP-based Purification mechanic (Jaaslet)
    - XP gained will charge up purification at Pokemon Lab and Agate Village
    - XP cost for purifying pokemon will increase, based on total number of purified pokemon
    - A consumable item (Based on but not called the Time Flute) will be added to dungeon chests in Orre, which will charge purification meters significantly
    - Maybe make a held item that helps too, TBD
- [x] Create a standards guide and examples for Shadow pokemon sprites (Drak4y, see [link](https://discord.com/channels/450412847017754644/1093853057005146122))
- [x] Create all 131 Shadow pokemon sprites for all genders and shinys (Many artists)
- [x] Invent and add a Miror B Mechanic (resolved)
- [ ] Create Mt. Battle as a multi-floor dungeon that gives BP from chests (Martius)
- [x] Add gyms with Cipher Admins
- [x] Add Shadow Quests
- [x] Add Poke Spots
- [x] Add uncaught shadowmon map filter (Martius)
- [x] Add shops and NPCs for Colosseum
- [x] Add shops and NPCs for XD
- [x] Re-vamp Purification Mechanic (Jaas)
- [x] Colosseum NPC Sprites
- [x] XD NPC Sprites
- [ ] Crew Testing
- [x] Add Caught Shadows indicator to dungeons
- [x] Figure out what to do with the Orre Colosseum

### Issues Required For This Task

There's some that have mentioned shadowmons, but I'm not gonna reference them.
