### ISSUE TITLE
[TASK]: In-progress projects as of 0.10.10.

### ISSUE THREAD

**Issue by Farboo171** [pokeclicker/pokeclicker#4232]
### Task Description

This is a consolidated list of projects that are currently being worked on, but are not yet complete. As some of these projects may not have associated Issues or PRs, this  will help focus development.

### Notes

Nothing new will be added to this list, this is strictly for what is currently in progress. This will help the development team identify what projects are needing attention.

### Issues Required For This Task

- [ ] Hisui: #4128 (Qwerty is main CC, Soul is on map making)
- [ ] Orre: #4002 (Eugene is main CC, Drakay, Soul, and other volunteers on sprites)
- [x] Safari Improvements: #3812 , #3998 (Partially complete, Martius to finish)
- [ ] Contests: #3690 (Eugene/Timespazm)
- [x] Light Ball Improvement: #3380 , #3882 (Decided to no longer do this)
- [ ] Mega Stones: #3368 (Qwerty managing checklist)
- [ ] Legendary Pokemon Quests and Mechanics: #3320, #3329, #3333 (Open projects for new-ish CCs, Eugene managing checklist)
- [ ] Visual Improvements for Gym Battles: #2156 (Osherwott)
- [x] Desert Environment: #3297 (Osherwott)
- [x] Event Calendar: #348 (Initially done, #4374 for finalizing)
- [x] Friend Safari (Jaas main CC, periodic testing by Crew)
- [ ] Alola Story Quests: #4072 (Osherwott)
