### ISSUE TITLE
[TASK]: Quest Rebalancing

### ISSUE THREAD

**Issue by Farboo171** [pokeclicker/pokeclicker#4332]
### Task Description

In an effort to make QP gain more balanced, and to potentially find a use for Quest Level in the future, some quests need to be rebalanced. Some are too highly rewarding for their effort, some are too low, and some are absolute nonsense. Many of the existing quests, however, can serve as a reference point for "balanced enough".

The following quests need to be rebalanced, as described:

- [x] Catch # Pokemon of a type. Rewards should be increased.
- [x] Gain Farm Points. Rewards should be increased.
- [x] Gain # gems of a type. Rewards should be decreased.
- [x] Gain # Pokedollars. Rewards should be increased. Martius is working on this, based on #3585 
- [x] Gain # DT. Rewards should be changed up. Martius is working on this, based on #3585 
- [x] Grow # berries of X type. Rewards should be increased, but also probably a full rework is needed.
- [x] Hatch # Eggs. Rewards should be decreased

When "Rewards should be decreased/increased" is used, that refers to QP per effort, not explicitly QP. This could be higher rewards for the same number of catches, or fewer catches to get the same number of QP.

### Notes

This table can be used for reference

![image](https://github.com/pokeclicker/pokeclicker/assets/109317224/fcb3b0fe-4c14-4243-8b2b-3b6ea5bfe6e1)

Also, this is not going to directly be #2088, but it will allow for some scaling like that to be figured out in the future, since we won't just be scaling up unbalanced quests.

### Issues Required For This Task

N/A

**Comment by xslk** [comment]
Blanket fix idea, level 30 (current highest quest level achievement) doubles QP reward from quest

**Comment by Farboo171** [comment]
> Blanket fix idea, level 30 (current highest quest level achievement) doubles QP reward from quest

Scaling unbalanced quests evenly will only make the balance issues worse. After balance is addressed, solutions like this can be considered.
