### ISSUE TITLE
Add Hoenn region

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker/pokeclicker#436]
### TODO list:

- [x] Map
  - [x] Add routes
  - [x] Add towns
  - [x] Add dungeons
  - [x] Add dock
- [ ] Towns
  - [x] Get list of towns
  - [x] Get images
  - [x] List of Gyms
  - [ ] Add stores
- [x] Gyms/Elite 4
  - [x] List of gyms
  - [x] List of Elite 4 members
  - [x] Add Gym leader teams
  - [x] Add Elite 4 teams
  - [x] Get images
- [x] Dungeons
  - [x] Get list of dungeons
  - [x] Filter dungeon list
  - [x] Add Pokemon to the dungeons
  - [x] Get images
- [x] Pokemon
  - [x] Get a list of Pokemon and stats etc.
  - [x] Get the sprites
- [x] Routes
  - [x] Add Pokemon to every route
  - [x] Add route requirements
    - [x] Routes
    - [x] Badges
    - [x] Dungeons
- [x] Eggs
  - [x] Add some Pokemon to each of the eggs
- [ ] Evolution stones
  - [ ] Do we need any new stones?
- [x] Legendary Pokemon
  - [x] Roaming Pokemon
  - [x] Dungeon Pokemon

### OTHER TODO:
- [ ] Adjust dungeon pokemon hp
- [ ] Adjust the gym leader/elite 4 pokemon hp
- [ ] Adjust the gym leader/elite 4 pokemon win reward amount
- [x] Adjust the way the HP is calculated on routes
