### ISSUE TITLE
[TASK]: A few tasks for aspiring contributors

### ISSUE THREAD

**Issue by Farboo171** [pokeclicker/pokeclicker#4745]
### Task Description

Here are a few tasks for aspiring contributors that are sure to be approved:

- [ ] Add a canon-friendly Naps trainer to the Cipher Lab dungeon, locked behind the quest step to defeat Lovrina in Gale of Darkness. This Naps should have Shadow Teddiursa.
- [ ] Increase the Flow Formula by a factor of 1.5 as a rebalance for Scents being able to be held by purified mons.
- [ ] Add Bonsley as a roamer in Orre unlocked after beating the Gale of Darkness quest

If this goes well, I'll make some more task lists like this for new-ish folks.

### Issues Required For This Task

Related to #4002

**Comment by RedzepR** [comment]
I'm interested in this issue but never worked with github before

I've done the necessary setup for the project, changed the files and commited (but not pushed) the changes locally. How would the usual process go? Is there somewhere I can read up on?

**Comment by Farboo171** [comment]
Have you followed the old guide?
https://pokeclicker.miraheze.org/wiki/Code_Contributors

That should get you most of the way there, and asking specific questions with screenshots in #development-help on Discord will get you over the line

**Comment by RedzepR** [comment]
Does one not need to claim an issue and/or link their changes to the specific issue?

**Comment by Farboo171** [comment]
General convention is that if you're doing something explicitly asked for, just link to where it was asked for in the PR description text. So you can enter "#4745" in the PR description and it will link to here.

In terms of claiming, it's kinda first come first serve.
