### ISSUE TITLE
[TASK]:  Some tasks in support of ongoing work

### ISSUE THREAD

**Issue by Farboo171** [pokeclicker/pokeclicker#4791]
### Task Description

Making a small list of tasks so they don't get lost, and so people looking for something to do can help out:

- [ ] Add an NPC in the Pokemon Village after beating the Mega Mewtwo quest explaining why there's an uncatchable mega Mewtwo there
- [ ] Add a method of seeing Base Statistics to the Pokedex. 
- [ ] Add lore-friendly loot to Pokemon Contest for 1, 10, and 25 wins in the Normal, Super, and Hyper ranks

### Notes

Please claim the task on this issue. not every task needs to be taken by the same person.

### Issues Required For This Task

N/A

**Comment by Farboo171** [comment]
Captured elsewhere, closing
